// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import CollapsibleController from "controllers/collapsible_controller"
application.register("collapsible", CollapsibleController)

import DayAccordionController from "controllers/day_accordion_controller"
application.register("day-accordion", DayAccordionController)

import ImageViewerController from "controllers/image_viewer_controller"
application.register("image-viewer", ImageViewerController)

import ThumbnailSizeController from "controllers/thumbnail_size_controller"
application.register("thumbnail-size", ThumbnailSizeController)