default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "default"
      threads: 1
      processes: 1
      polling_interval: 0.05
    - queues: "face_detection"
      threads: 1
      processes: 1
      polling_interval: 0.05
    - queues: "attachments"
      threads: 1
      processes: 1
      polling_interval: 0.05

development:
  <<: *default
  # Override worker concurrency for stability on macOS dev; tune with env vars
  workers:
    - queues: "default"
      threads: 1
      processes: 1
      polling_interval: 0.05
    - queues: "face_detection"
      threads: 1
      processes: 1
      polling_interval: 0.05
    - queues: "attachments"
      threads: 1
      processes: 1
      polling_interval: 0.05

test:
  <<: *default

production:
  <<: *default
