const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: [
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*'
  ],
  safelist: [
    // Base grid columns
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'grid-cols-7',
    'grid-cols-8',
    // Responsive grid columns
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'sm:grid-cols-4',
    'sm:grid-cols-5',
    'sm:grid-cols-6',
    'sm:grid-cols-7',
    'sm:grid-cols-8',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'md:grid-cols-5',
    'md:grid-cols-6',
    'md:grid-cols-7',
    'md:grid-cols-8',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'lg:grid-cols-5',
    'lg:grid-cols-6',
    'lg:grid-cols-7',
    'lg:grid-cols-8',
    // Gap utilities
    'gap-0',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'sm:gap-0',
    'sm:gap-1',
    'sm:gap-2',
    'sm:gap-3',
    'sm:gap-4',
    // Border utilities
    'border-0',
    'border-2',
    'sm:border-0',
    'sm:border-2',
    // Rounded utilities
    'rounded-none',
    'rounded-lg',
    'sm:rounded-none',
    'sm:rounded-lg',
    // Padding utilities
    'px-0',
    'px-2',
    'px-3',
    'px-4',
    'px-6',
    'sm:px-0',
    'sm:px-2',
    'sm:px-3',
    'sm:px-4',
    'sm:px-6',
    // Margin utilities
    'mb-3',
    'mb-6',
    'mb-8',
    'mb-12',
    'sm:mb-3',
    'sm:mb-6',
    'sm:mb-8',
    'sm:mb-12',
    // Text size utilities
    'text-xl',
    'text-2xl',
    'sm:text-xl',
    'sm:text-2xl',
    // Display utilities
    'hidden',
    'block',
    // For compact thumbnails mode
    'compact-thumbnails',
    // Admin tagger styles
    'bg-yellow-500',
    'text-black',
    'border-yellow-500',
    'bg-gray-800',
    'text-gray-400',
    'border-gray-700',
    'border-red-600',
    'border-l',
    'border-l-2',
    'border-red-600/50',
    'hover:border-yellow-500',
    'hover:bg-yellow-500',
    'hover:text-black',
    'hover:border-yellow-500',
    // Sidebar styles
    'w-64',
    'xl:w-96',
    'space-y-1',
    'space-y-3',
    'text-left',
    'flex-grow',
    'h-full',
    'overflow-y-auto',
    'max-w-full',
    'max-h-full',
    'max-h-96',
    'object-contain',
    'flex-col',
    'sm:hidden',
    'sm:block',
    'sm:flex',
    'sm:flex-col',
    'sm:flex-grow',
    'mt-auto',
    'xl:grid',
    'xl:grid-cols-2',
    'xl:gap-4',
    'grid-cols-2',
    'grid-cols-3'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Flapjack', 'Inter var', ...defaultTheme.fontFamily.sans],
        'flapjack': ['Flapjack', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: []
}